import type { InterfaceLanguageCode } from "@/lib/i18n/interface-language";

export const researchCopy = {
  fa: {
    nav: "پژوهش یادگیری تطبیقی",
    indexTitle: "پژوهش یادگیری تطبیقی",
    indexBody: "مرکز دسترسی به نتایج، راهنمای تفسیر و مصنوعات پژوهشی تولیدشده با داده‌های مصنوعی.",
    results: "نتایج پژوهش",
    resultsBody: "مدل‌ها، معیارها، الگوهای یادگیرنده و تصمیم‌های تطبیقی شبیه‌سازی‌شده را بررسی کنید.",
    guidance: "راهنمای پژوهش",
    guidanceBody: "روش، مدل‌ها، معیارها و محدودیت ادعاهای این مطالعه را به زبان روشن بخوانید.",
    artifacts: "مصنوعات پژوهشی",
    learners: "یادگیرندگان مصنوعی",
    interactions: "تعامل‌های شبیه‌سازی‌شده",
    figures: "نمودارها",
    tables: "جدول‌ها",
    datasets: "مجموعه‌داده‌ها",
    seed: "بذر بازتولید",
    open: "باز کردن",
    download: "دریافت",
    report: "گزارش نهایی",
    latestRun: "آخرین اجرای ثبت‌شده",
    syntheticNotice: "این نتایج از داده‌های مصنوعی به دست آمده‌اند و اثربخشی آموزشی در دنیای واقعی را اثبات نمی‌کنند.",
    modelResults: "نتایج مدل‌ها",
    guidanceTitle: "چگونه پژوهش را بخوانیم",
    purpose: "هدف و دامنه",
    purposeBody: "این نمونه بررسی می‌کند که آیا یک خط لوله یادگیری ماشین می‌تواند الگوهای ضعف و رفتار تزریق‌شده به یادگیرندگان مصنوعی را بازیابی کند.",
    pipeline: "خط لوله پژوهش",
    pipelineBody: "یادگیرندگان و تعامل‌ها تولید می‌شوند، ویژگی‌ها ساخته می‌شوند، مدل‌ها آموزش می‌بینند و سپس جدول‌ها، نمودارها و گزارش بازتولیدپذیر تولید می‌شوند.",
    interpretation: "تفسیر نتایج",
    interpretationBody: "امتیازهای بالا یعنی مدل الگوهای طراحی‌شده در شبیه‌سازی را بازیابی کرده است؛ نه اینکه سامانه با یادگیرندگان واقعی اعتبارسنجی شده باشد.",
    validity: "محدودیت اعتبار",
    validityBody: "فرض‌های مصنوعی، برچسب‌های تولیدشده و سنجه‌های جانشین بر نتیجه اثر می‌گذارند. اعتبارسنجی با داده واقعی کار آینده است.",
    models: "راهنمای مدل‌ها",
    classification: "طبقه‌بندی ضعف",
    regression: "پیش‌بینی پیامد",
    clustering: "خوشه‌بندی الگوی یادگیرنده"
  },
  en: {
    nav: "Adaptive Learning Research",
    indexTitle: "Adaptive Learning Research",
    indexBody: "One admin workspace for results, interpretation guidance, and Research Artifacts generated from synthetic data.",
    results: "Research results",
    resultsBody: "Inspect models, metrics, learner archetypes, and simulated adaptive decisions.",
    guidance: "Research guidance",
    guidanceBody: "Read the method, models, metrics, and limits of the study’s claims in plain language.",
    artifacts: "Research Artifacts",
    learners: "Synthetic learners",
    interactions: "Simulated interactions",
    figures: "Figures",
    tables: "Tables",
    datasets: "Datasets",
    seed: "Reproduction seed",
    open: "Open",
    download: "Download",
    report: "Final report",
    latestRun: "Latest committed run",
    syntheticNotice: "These results come from synthetic data and do not prove real-world learning effectiveness.",
    modelResults: "Model results",
    guidanceTitle: "How to read the research",
    purpose: "Purpose and scope",
    purposeBody: "The prototype tests whether a machine-learning pipeline can recover weakness and behavior patterns injected into synthetic learners.",
    pipeline: "Research pipeline",
    pipelineBody: "Learners and interactions are generated, features are engineered, models are trained, and reproducible tables, figures, and a report are produced.",
    interpretation: "Interpreting results",
    interpretationBody: "High scores mean a model recovered patterns designed into the simulation—not that the system has been validated with real learners.",
    validity: "Threats to validity",
    validityBody: "Synthetic assumptions, generated labels, and proxy metrics shape the result. Validation with real learner data remains future work.",
    models: "Model guide",
    classification: "Weakness classification",
    regression: "Outcome regression",
    clustering: "Learner-pattern clustering"
  },
  de: {
    nav: "Adaptive-Learning-Forschung",
    indexTitle: "Adaptive-Learning-Forschung",
    indexBody: "Ein Admin-Bereich für Ergebnisse, Interpretationshilfen und Forschungsartefakte aus synthetischen Daten.",
    results: "Forschungsergebnisse",
    resultsBody: "Modelle, Metriken, Lernarchetypen und simulierte adaptive Entscheidungen untersuchen.",
    guidance: "Forschungsleitfaden",
    guidanceBody: "Methode, Modelle, Metriken und Grenzen der Studien­aussagen verständlich lesen.",
    artifacts: "Forschungsartefakte",
    learners: "Synthetische Lernende",
    interactions: "Simulierte Interaktionen",
    figures: "Abbildungen",
    tables: "Tabellen",
    datasets: "Datensätze",
    seed: "Reproduktions-Seed",
    open: "Öffnen",
    download: "Herunterladen",
    report: "Abschlussbericht",
    latestRun: "Letzter gespeicherter Lauf",
    syntheticNotice: "Diese Ergebnisse stammen aus synthetischen Daten und belegen keine reale Lernwirksamkeit.",
    modelResults: "Modellergebnisse",
    guidanceTitle: "Forschung richtig lesen",
    purpose: "Zweck und Umfang",
    purposeBody: "Der Prototyp prüft, ob eine Machine-Learning-Pipeline in synthetische Lernende eingebettete Schwäche- und Verhaltensmuster wiederfindet.",
    pipeline: "Forschungspipeline",
    pipelineBody: "Lernende und Interaktionen werden erzeugt, Merkmale entwickelt, Modelle trainiert und reproduzierbare Tabellen, Abbildungen und ein Bericht erstellt.",
    interpretation: "Ergebnisse interpretieren",
    interpretationBody: "Hohe Werte bedeuten, dass ein Modell entworfene Simulationsmuster erkennt – nicht, dass es mit echten Lernenden validiert wurde.",
    validity: "Validitätsrisiken",
    validityBody: "Synthetische Annahmen, erzeugte Labels und Proxy-Metriken prägen das Ergebnis. Reale Lerndaten bleiben zukünftige Arbeit.",
    models: "Modellleitfaden",
    classification: "Schwächenklassifikation",
    regression: "Ergebnisregression",
    clustering: "Lernmuster-Clustering"
  }
} satisfies Record<InterfaceLanguageCode, Record<string, string>>;
